### ISSUE TITLE
Not making unique seq fasta for AA_seqs_and_ref_nuc local variable 'i' referenced before assignment

### ISSUE THREAD

**Issue by jacmm** [shimbalama/screen_assembly#8]
HI Liam, 

Recently I have had an issue with some query proteins, looking at the output notes for the proteins with an issue I am getting the following message:
Not making unique seq fasta for SpeC_seqs_and_ref_nuc local variable 'i' referenced before assignment

This time I had an issue with 3 out of 23 proteins. I have checked the inputs, which are fine, no odd characters . Also the proteins that have an issue changes across different runs.

Any insights on what is going on and how to fix it?
Please let me know if you need any more information.

Thank you, 
Jacqui

**Comment by shimbalama** [comment]
Hi Jacqui,

This looks like the same issue as #7 (https://github.com/shimbalama/screen_assembly/issues/7). 

If that is the issue then it is simply a case of there being no hit for the relative sequence at the given threshold. Please review issue #7 and see if you agree that this is the case. If not I'm happy to look into it. In reading that thread you will see that my excuse for such sloppy programming is that (1) I was junior when I wrote the code and (2) I have long since left the lab (and therefore funding that would support further code development).

The good news is that I now have a new job that might allow me to spend some time on this so hopefully one day I can give this script a good polish.

Regards,
Liam
